### ISSUE TITLE
`gasleft` calculation incorrect

### ISSUE THREAD

**Issue by alexbabits** [symbioticfi/core#67]
`baseDelegator::onSlash()`: https://github.com/symbioticfi/core/blob/bda957eafac570ec40c1f59a4d39a90c244a3361/src/contracts/delegator/BaseDelegator.sol#L197

Can cause rare reverts where it "should" go through according to 63/64 rule, but reverts even if there would be enough gas.

```diff
-    if (gasleft() < HOOK_RESERVE + HOOK_GAS_LIMIT * 64 / 63) {
+    if (gasleft() < HOOK_RESERVE + HOOK_GAS_LIMIT * 63 / 64) {
```

It's forcing `gasleft` to be GTE (buffer + 64/63) instead of (buffer + 63/64). Doesn't really matter since you have buffer `HOOK_RESERVE`, which is plenty for rest of function?

**Comment by 1kresh** [comment]
HOOK_RESERVE is considered a buffer until the external call processing. Therefore, we may simplify the check condition to gasleft() < HOOK_GAS_LIMIT * 64 / 63 (assuming the buffer to be equal to zero). Therefore, this check just means that it must be possible to send HOOK_GAS_LIMIT to the call (as the possible gas to send is min(gasleft() * 63 / 64, HOOK_GAS_LIMIT)).
